version: "3"

dotenv:
  - ".env"

env:
  APPLICATIONS_PATH: "/usr/share/applications"

tasks:
  ls:
    cmds:
    - ls -l $APPLICATIONS_PATH/
  intellij-idea:
    aliases:
      - idea
    cmds:
      - echo $IDEA_HOME
      - export IDEA_HOME
      - sudo cp apps/IntelliJ-IDEA.desktop $APPLICATIONS_PATH/IntelliJ-IDEA.desktop
      - sudo cat $APPLICATIONS_PATH/IntelliJ-IDEA.desktop
      - sudo -E envsubst < $APPLICATIONS_PATH/IntelliJ-IDEA.desktop > temp.desktop && sudo mv temp.desktop $APPLICATIONS_PATH/IntelliJ-IDEA.desktop
      - sudo cat $APPLICATIONS_PATH/IntelliJ-IDEA.desktop
      - task: update
  pycharm:
    cmds:
      - echo $PYCHARM_HOME
      - export PYCHARM_HOME
      - sudo cp apps/PyCharm.desktop $APPLICATIONS_PATH/PyCharm.desktop
      - sudo cat $APPLICATIONS_PATH/PyCharm.desktop
      - sudo -E envsubst < $APPLICATIONS_PATH/PyCharm.desktop > temp.desktop && sudo mv temp.desktop $APPLICATIONS_PATH/PyCharm.desktop
      - sudo cat $APPLICATIONS_PATH/PyCharm.desktop
      - task: update
  rust-rover:
    cmds:
      - echo $RUSTROVER_HOME
      - export RUSTROVER_HOME
      - sudo cp apps/RustRover.desktop $APPLICATIONS_PATH/RustRover.desktop
      - sudo cat $APPLICATIONS_PATH/RustRover.desktop
      - sudo -E envsubst < $APPLICATIONS_PATH/RustRover.desktop > temp.desktop && sudo mv temp.desktop $APPLICATIONS_PATH/RustRover.desktop
      - sudo cat $APPLICATIONS_PATH/RustRover.desktop
      - task: update
  update-desktop-menu:
    aliases:
      - update
    cmds:
      - xdg-desktop-menu forceupdate
